### ISSUE TITLE
Vérifier les formats UNC et temps de transfert dans le fichier de logs journalier

### ISSUE THREAD

**Issue by DESPREZJulien** [nlorit/EasySave#16]
Le logiciel doit écrire en temps réel dans un fichier log journalier l’historique des actions des travaux de sauvegarde. Les informations minimales attendues sont :
- Horodatage.
- Nom de sauvegarde.
- Adresse complète du fichier source (format UNC).
- Adresse complète du fichier de destination (format UNC).
- Taille du fichier.
- Temps de transfert en ms (négatif si erreur).

**Comment by nlorit** [comment]
#24

**Comment by nlorit** [comment]
- [ ] Transfer is negatif if error
